FROM node:14 as build

WORKDIR /client

COPY package*.json ./
COPY public ./
COPY src ./

COPY tsconfig.json .

RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /client/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
CMD ["nginx", "-g", "daemon off;"]