# Build the client
FROM node:14 as build

WORKDIR /client

COPY package*.json ./
COPY public ./public
COPY src ./src
COPY scripts ./scripts
COPY config ./config

COPY nginx.conf .
COPY tsconfig.json .

RUN npm install
RUN npm run build

# Start the webserver
FROM nginx:stable-alpine

COPY --from=build /client/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]