version: '3'

networks:
    jsramverk:

services:
    client:
        build: ./client
        entrypoint: npm run start
        environment: 
            - REACT_APP_NO_CLEAR_CONSOLE=true
        stdin_open: true
        volumes: 
            - ./client:/client
        ports: 
            - 3000:3000
        depends_on: 
            - server

    server:
        build: ./server
        entrypoint: npm run dev
        tty: true
        environment: 
            - MONGODB=mongodb
            - PORT=3001
            - JWT_SECRET=CzYkstejACqaKmCmIzoeVlVp
        # volumes: 
            # - ./server:/server
        links: 
            - mongodb
        ports: 
            - 3001:3001
        networks:
            - jsramverk

    mongodb:
        image: mongo:3.6-xenial
        logging: 
            driver: none
        networks:
            - jsramverk

    test:
        build: ./server
        entrypoint: []
        command: sh -c "sleep 30 && npm run test"
        tty: true
        environment: 
            - MONGODB=mongodb
            - PORT=3001
            - TEST_DOMAIN=http://server:3001
        links: 
            - server
        depends_on: 
            - server
        networks:
            - jsramverk
