version: '3'

services:
    client:
        build: ./client
        entrypoint: npm run start
        environment: 
            - REACT_APP_NO_CLEAR_CONSOLE=true
        stdin_open: true
        volumes: 
            - ./client:/client
        ports: 
            - 3000:3000
    server:
        build: ./server
        entrypoint: npm run dev
        tty: true
        environment: 
            - MONGODB=mongodb
            - PORT=3001
        volumes: 
            - ./server:/server
        links: 
            - mongodb
        ports: 
            - 3001:3001

    mongodb:
        image: mongo:3.6-xenial
        logging: 
            driver: none

    test:
        build: ./server
        entrypoint: []
        command: sh -c "sleep 10 && ls"
        tty: true
        environment: 
            - MONGODB=mongodb
            - PORT=3001
            - TEST_DOMAIN=http://server:3001
        links: 
            - server
        depends_on: 
            - server
